# Generated by Django 4.2.5 on 2023-09-15 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name_plural": "comment"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Post"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name_plural": "tag"},
        ),
    ]
