# Generated by Django 4.2.5 on 2023-09-15 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentprofile",
            options={"verbose_name_plural": "AgentProfile"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "city"},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "property"},
        ),
        migrations.AlterModelOptions(
            name="propertystatus",
            options={"verbose_name_plural": "ropertyStatus"},
        ),
        migrations.AlterModelOptions(
            name="propertytype",
            options={"verbose_name_plural": "PropertyType"},
        ),
    ]
