# Generated by Django 4.2.5 on 2023-09-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendship",
            options={"verbose_name_plural": "Friendship"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name_plural": "Message"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name_plural": "UserProfile"},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
