# Generated by Django 4.2.5 on 2023-09-15 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_alter_friendship_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="profile_picture",
            new_name="profile_pic",
        ),
    ]
